In [1]:
import numpy as np

In [17]:
ls=range(20)

In [19]:
arr = np.array(ls)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
type(arr)

numpy.ndarray

In [24]:
b=arr[0:11]

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b[:] = range(101,112)

In [35]:
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [36]:
arr

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [37]:
arr[0:10:2]

array([101, 103, 105, 107, 109])

In [67]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [80]:
print(arr2[0:,1:])

[[ 2  3  4  5]
 [ 7  8  9 10]]
